# Generated by Django 3.0.2 on 2021-04-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='用户名称')),
                ('phone', models.CharField(max_length=50, verbose_name='用户电话')),
                ('age', models.CharField(max_length=50, verbose_name='年龄')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
        ),
    ]
